apiVersion: apps/v1
kind: Deployment
metadata:
  name: corporate-website
  labels:
    app: corporate-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: corporate-website
  template:
    metadata:
      labels:
        app: corporate-website
    spec:
      containers:
      - name: website
        image: rastogivinayak/corporate-website:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
